POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Atte Aaltonen",
    "number": "123 4567"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number": "123 4567"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Atte Aaltonen",
    "number": ""
}
